fix: commit massages setup with colors and emoji

diff --git a/.husky/_/commit-msg b/.husky/_/commit-msg
--- a/.husky/_/commit-msg
+++ b/.husky/_/commit-msg
@@ -1,9 +1,18 @@
 #!/usr/bin/env sh
+
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+NC='\033[0m'
+
+
 if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid." >&2
+    echo -e "${RED}❌ Aborting commit. Your commit message is invalid.${NC}" >&2
     exit 1
 fi
 if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
-    echo "Aborting commit. Your commit message is too long." >&2
+    echo -e "${RED}❌ Aborting commit. Your commit message is too long.${NC}" >&2
     exit 1
 fi
+
+echo -e "${GREEN}✅ Commit message is valid!${NC}"
